version: '3.3'

services:
  app:
    build: .
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network  

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: $USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $PASSWORD
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
networks:
  app-network: