version: '3.8'

services:
  app:
    build: .
    ports:
      - $PORT:$PORT
    env_file:
      - src/.env
    depends_on:
      - mongo
    networks:
      - app-network  

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
networks:
  app-network: